# Generated by Django 5.2 on 2025-12-30 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicines", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicine",
            name="batch_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
