# Generated by Django 5.2 on 2025-12-30 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="discount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="sale",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "Espèces"),
                    ("card", "Carte Bancaire"),
                    ("insurance", "Assurance"),
                    ("transfer", "Virement"),
                ],
                default="cash",
                max_length=20,
            ),
        ),
    ]
