# Generated by Django 5.2.8 on 2026-01-18 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0002_sale_discount_sale_payment_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "Espèces"),
                    ("card", "Carte Bancaire"),
                    ("insurance", "Assurance"),
                    ("transfer", "Virement"),
                    ("lumicash", "Lumicash"),
                ],
                default="cash",
                max_length=20,
            ),
        ),
    ]
