# Generated by Django 5.2.8 on 2025-12-30 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "suppliers",
            "0002_supplier_address_supplier_created_at_supplier_email_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplier",
            name="address",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="contact_info",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="email",
            field=models.EmailField(default="", max_length=254),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="phone",
            field=models.CharField(default="", max_length=20),
        ),
    ]
