# Generated by Django 5.2.8 on 2025-12-31 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_customuser_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[("admin", "Admin"), ("pharmacist", "Pharmacist")],
                default="pharmacist",
                max_length=20,
            ),
        ),
    ]
