# Generated by Django 6.0.3 on 2026-03-07 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('low_stock', 'Low Stock'), ('expired', 'Expired Medicine'), ('sale', 'New Sale'), ('system', 'System')], default='system', max_length=20),
        ),
    ]
